
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.security.AlgorithmParameterGenerator;
import java.security.AlgorithmParameters;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PublicKey;
import java.security.spec.X509EncodedKeySpec;
import javax.crypto.Cipher;
import javax.crypto.KeyAgreement;
import javax.crypto.SecretKey;
import javax.crypto.interfaces.DHPublicKey;
import javax.crypto.spec.DHParameterSpec;

public class frmBob extends javax.swing.JFrame {

    KeyAgreement bobKeyAgree;
    PublicKey alicePublicKey;
    SecretKey bobDesKey;
    Cipher bobCipher;

    public frmBob() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKhoaBob = new javax.swing.JTextField();
        txtKhoaAlice = new javax.swing.JTextField();
        txtKhoaKAB = new javax.swing.JTextField();
        txtMaHoaKAB = new javax.swing.JTextField();
        btnTaoKhoaB = new javax.swing.JButton();
        btnHienThiKhoaA = new javax.swing.JButton();
        btnKhoaChung = new javax.swing.JButton();
        btnMaHoaKAB = new javax.swing.JButton();
        btnMaHoaGiaiMa = new javax.swing.JButton();

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Bob");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Khóa Bob");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Khóa Alice");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Khóa KAB");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Mã Hóa KAB");

        txtKhoaBob.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        txtKhoaAlice.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        txtKhoaKAB.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        txtMaHoaKAB.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        btnTaoKhoaB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTaoKhoaB.setText("Tạo Khóa B");
        btnTaoKhoaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoKhoaBActionPerformed(evt);
            }
        });

        btnHienThiKhoaA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHienThiKhoaA.setText("Hiển thị KA");
        btnHienThiKhoaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiKhoaAActionPerformed(evt);
            }
        });

        btnKhoaChung.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnKhoaChung.setText("Hiển thị Khóa chung");
        btnKhoaChung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaChungActionPerformed(evt);
            }
        });

        btnMaHoaKAB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMaHoaKAB.setText("Mã hóa KAB");
        btnMaHoaKAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoaKABActionPerformed(evt);
            }
        });

        btnMaHoaGiaiMa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMaHoaGiaiMa.setText("Mã Hóa / Giải Mã");
        btnMaHoaGiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoaGiaiMaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtKhoaKAB, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtKhoaAlice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtKhoaBob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaHoaKAB, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnTaoKhoaB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHienThiKhoaA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMaHoaKAB, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKhoaChung))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(btnMaHoaGiaiMa)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(52, 52, 52))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtKhoaBob, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(btnTaoKhoaB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKhoaAlice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHienThiKhoaA, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKhoaKAB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKhoaChung, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtMaHoaKAB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMaHoaKAB, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(btnMaHoaGiaiMa)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoKhoaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoKhoaBActionPerformed
        try {
            boolean read = false; //doi cho toi khi co tap tin alice.pub 
            while (!read) {
                try {
                    String fileKeyAlice = "C:\\KeyAlice.txt";
                    FileInputStream fis = new FileInputStream(fileKeyAlice);
                    fis.close();
                    read = true;
                } catch (Exception ex) {

                }
            }
            String fileName = "C:\\KeyAlice.txt";
            FileInputStream fis = new FileInputStream(fileName);
            byte[] alicePubKeyEnc = new byte[fis.available()];
            fis.read(alicePubKeyEnc);
            fis.close();

            KeyFactory bobKeyFac = KeyFactory.getInstance("DH");
            X509EncodedKeySpec x509KeySpec = new X509EncodedKeySpec(alicePubKeyEnc);
            alicePublicKey = bobKeyFac.generatePublic(x509KeySpec);
            DHParameterSpec dhParamSpec = ((DHPublicKey) alicePublicKey).getParams();

            System.out.println("Generate a DH KeyPair...");
            KeyPairGenerator bobKpairGen = KeyPairGenerator.getInstance("DH");            
            bobKpairGen.initialize(dhParamSpec);
            
            KeyPair bobKpair = bobKpairGen.generateKeyPair();
            System.out.println("Initializing KeyAgreement Engine ...");
            bobKeyAgree = KeyAgreement.getInstance("DH");
            bobKeyAgree.init(bobKpair.getPrivate());

            byte[] bobPubKeyEnc = bobKpair.getPublic().getEncoded();
            //String fileName = "C:\\Users\\admin\\Desktop\\Long\\Thuc hanh\\TH bao mat thong tin\\tuan 4\\txt\\KeyBob.pub";
            String filenameb = "C:\\KeyBob.txt";
            FileOutputStream fos = new FileOutputStream(filenameb);
            fos.write(bobPubKeyEnc);
            fos.close();
            txtKhoaBob.setText(bobPubKeyEnc.toString());
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btnTaoKhoaBActionPerformed

    private void btnHienThiKhoaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiKhoaAActionPerformed
        try {
            //String fileName = "C:\\Users\\admin\\Desktop\\Long\\Thuc hanh\\TH bao mat thong tin\\tuan 4\\txt\\KeyAlice.pub";
            String fileName = "C:\\KeyAlice.txt";
            FileInputStream fis = new FileInputStream(fileName);
            byte[] akeyP = new byte[fis.available()];
            fis.read(akeyP);
            fis.close();
            txtKhoaAlice.setText(akeyP.toString());
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btnHienThiKhoaAActionPerformed

    private void btnKhoaChungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaChungActionPerformed
         try {
            bobKeyAgree.doPhase(alicePublicKey, true);
            byte[] bobSharedSecret = bobKeyAgree.generateSecret();
            System.out.println("Khoa chung:Shared secret (DEBUG ONLY): " + CryptoUtil.toHexString(bobSharedSecret));
            txtKhoaKAB.setText(CryptoUtil.toHexString(bobSharedSecret));
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_btnKhoaChungActionPerformed

    private void btnMaHoaKABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoaKABActionPerformed
        try {
            bobKeyAgree.doPhase(alicePublicKey, true);
            bobDesKey = bobKeyAgree.generateSecret("DES");
            txtMaHoaKAB.setText(bobDesKey.toString()); // khoa chung A-B 
            BufferedWriter bw = null; //ghi van ban da ma hoa 
            String fileName = "C:\\KhoaABBob.txt"; 
            //luu van ban
            bw = new BufferedWriter(new FileWriter(fileName)); // ghi van ban 
            bw.write(bobDesKey.toString());
            bw.close();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btnMaHoaKABActionPerformed

    private void btnMaHoaGiaiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoaGiaiMaActionPerformed
        frmDESCS des = new frmDESCS();
        des.setVisible(true);
    }//GEN-LAST:event_btnMaHoaGiaiMaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHienThiKhoaA;
    private javax.swing.JButton btnKhoaChung;
    private javax.swing.JButton btnMaHoaGiaiMa;
    private javax.swing.JButton btnMaHoaKAB;
    private javax.swing.JButton btnTaoKhoaB;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtKhoaAlice;
    private javax.swing.JTextField txtKhoaBob;
    private javax.swing.JTextField txtKhoaKAB;
    private javax.swing.JTextField txtMaHoaKAB;
    // End of variables declaration//GEN-END:variables
}
